### ISSUE TITLE
Dúvida: @StateObject x @ObservedObject

### ISSUE THREAD

**Issue by raonivaladares** [pauloSantosMobileTW/MoviesSwiftUI#1]
https://github.com/pauloSantosMobileTW/MoviesSwiftUI/blob/9d86b32ee974a078655f956a29d64075a1e1d4b8/Movies-SwiftUI/Modules/MovieList/MovieListView.swift#L4

Eu estava lendo um artigo sobre property wrappers e me deparei com esse ponto: 

```
Previously you might have used @ObservedObject to get the same result, but that was dangerous – sometimes, and only sometimes, @ObservedObject could accidentally release the object it was storing, because it wasn’t designed to be the ultimate source of truth for the object. This won’t happen with @StateObject, so you should use it instead.
```

https://www.hackingwithswift.com/quick-start/swiftui/what-is-the-stateobject-property-wrapper

Faria sentido trocar para viewModel de @ObservedObject -> @StateObject?

**Comment by pauloSantosMobileTW** [comment]
Bom dia Raoni, eu não conhecia esse **@StateObject**, vou dar uma olhada.

O engraçado é que o mesmo site indica o @ObservedObject:
[https://www.hackingwithswift.com/books/ios-swiftui/sharing-swiftui-state-with-observedobject](https://www.hackingwithswift.com/books/ios-swiftui/sharing-swiftui-state-with-observedobject)

**Comment by VitorFerraz** [comment]
Bom dia, Raoni o @StateObject está disponível somente para iOS 14 e Xcode 12, por isso estavamos usando o @ObservedObject. 
https://developer.apple.com/documentation/swiftui/stateobject

**Comment by raonivaladares** [comment]
estou montando um exemplo, estou preso justamente nessa parte e fiquei na dúvida em qual usar. 

Pessoas, obrigado pelas respostas! o/
